### ISSUE TITLE
[Personal Tokens] Attention message

### ISSUE THREAD

**Issue by gabrielnes-azion** [aziontech/azion-console-kit#522]
Please fix the alert message to proper English.
Suggestion:
"After closing, you can no longer view or copy your personal token."

<img width="589" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/081988aa-d4b5-403e-bc78-162254f7ebb3">

Also, the "I agree"-button sounds like a confirmation of the terms of service. 
Suggestion:
"OK" / "Close" / "Understood"

**Comment by matheus-sunderhus** [comment]
Thank you for the request. I am closing this issue as we have already created and assigned the refactor task to a developer.
