### ISSUE TITLE
CSR code can be deleted from EditDigitalCertificate and entry type changes

### ISSUE THREAD

**Issue by bru-andrade** [aziontech/azion-console-kit#544]
**Environment: Production**

When I create a CSR and delete the request code from the CSR field, the type of certificate entry changes to Edge Certificate and I can no longer access the CSR generated, as if the CSR is a private key.

## Steps to reproduce

1. Go to Digital Certificates
2. Create a new certificate
3. Select generate CSR option
4. Fill form
5. Click Save
6. Delete CSR code from CSR field

## Expected result

CSR is read-only field

OR

When saving, show message that the CSR cannot be removed and the entry must be deleted for that to occur

OR

When saving, go back to certificate list. When clicking the CSR entry, the deleted code should still be visible

## Actual Result

The CSR is no longer visible and the page layout changes to certificate + private key.

## Attachments

https://github.com/aziontech/azion-console-kit/assets/119969414/edd140b6-d033-41af-996b-cde061cbd01f

https://github.com/aziontech/azion-console-kit/assets/119969414/e3a5a132-e5d5-437f-b9b0-627ac406ac4f

**Comment by csfeijo** [comment]
Converted to internal issue: UXE-1721

**Comment by bru-andrade** [comment]
Issue closed by #695 

<img width="1440" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/119969414/c03448e0-89a4-49e9-acc4-4a1c5cdd95fc">

- Field is now read-only
- Copy to clipboard button still copies certificate content
- When certificate is added, CSR entry becomes digital certificate
