### ISSUE TITLE
Problema ao tentar salvar um qtype MX no iDNS

### ISSUE THREAD

**Issue by marcusgrando** [aziontech/azion-console-kit#627]
Ao tentar editar uma entrada qtype MX no iDNS dá um erro mesmo de uma entrada igual a já existente.
<img width="1467" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/3065058/49225bfb-5753-449f-ab98-de800ae8c50b">

**Comment by csfeijo** [comment]
Converted to internal issue: UXE-1655

**Comment by csfeijo** [comment]
Fixed and deployed to production - Release 1.8.4 (console.azion.com)
