### ISSUE TITLE
Path field wrongly required in Allowed Rules

### ISSUE THREAD

**Issue by rogerclaus** [aziontech/azion-console-kit#647]
User is unable to save an Allowed Rule without setting the Path field, even though its description says it can be blank.

<img width="594" alt="Screenshot 2024-01-31 at 12 38 40" src="https://github.com/aziontech/azion-console-kit/assets/29800579/b680805c-210e-42c9-945e-c0d99cbe66ff">

**Comment by csfeijo** [comment]
Converted to internal issue: UXE-1722

**Comment by morganajohann** [comment]
Resolvido na [https://aziontech.atlassian.net/browse/UXE-1722](url)
