### ISSUE TITLE
The networklist IP List should be bigger

### ISSUE THREAD

**Issue by gabrielnes-azion** [aziontech/azion-console-kit#663]
This is how the UI is rendered:
<img width="1382" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/b5bb4aac-efa9-47b7-99c4-f179d8b1bcc4">

This is how it should be rendered:
<img width="1404" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/8365359f-c563-4a21-9235-09d43afc63cf">

**Comment by csfeijo** [comment]
Converted to internal issue: UXE-1586

**Comment by csfeijo** [comment]
Fixed and deployed in prodution on release 1.8.5.
