### ISSUE TITLE
Help Center articles not showing for some routes

### ISSUE THREAD

**Issue by bru-andrade** [aziontech/azion-console-kit#728]
https://jam.dev/c/a5d5cb46-6b27-4f19-b50a-2fed2067d4bc

Routes without Help Center:

- personal-tokens/create
- edge-functions/create
- edge-functions/edit
- marketplace/solution

Help Center articles repo: https://github.com/aziontech/docs_help_center

**Comment by csfeijo** [comment]
Converted to internal issue: UXE-1808

**Comment by morganajohann** [comment]
https://aziontech.atlassian.net/browse/UXE-1808

**Comment by morganajohann** [comment]
Ajustes necessários já foram feitos e validados. Sendo assim, fechando a issue aqui :)
