### ISSUE TITLE
Using dark mode, Real Time Metrics graphs display the left column in black

### ISSUE THREAD

**Issue by rodrigomaria** [aziontech/azion-console-kit#742]
RTMetrics graphs display the left column in black, making easy reading impossible.

![Screenshot 2024-02-19 at 16 25 21](https://github.com/aziontech/azion-console-kit/assets/14929998/2f9727c8-c0a0-43e6-9695-514ca266e497)

**Comment by morganajohann** [comment]
Aberta issue interna para ajuste.

**Comment by morganajohann** [comment]
Resolvido na issue [https://aziontech.atlassian.net/browse/UXE-1959](url)
