### ISSUE TITLE
Tipo de Origin não encontrado.

### ISSUE THREAD

**Issue by tiagokrebs** [aziontech/azion-console-kit#764]
Na UI de manager.azion.com, nas Origins de uma Edge Application, existe o `Origin Type: Object Storage`, porém, em console.azion.com esse tipo não existe, deixado o campo em branco.
Console:
![image](https://github.com/aziontech/azion-console-kit/assets/55988677/afc45f1f-6668-4659-bd3d-e28bcac79b84)
Manager: 
![image](https://github.com/aziontech/azion-console-kit/assets/55988677/0e0c2408-eaac-4f8a-9b25-97aa4c41818a)

**Comment by matheus-sunderhus** [comment]
Bug criado internamente para resolução de problema.

https://aziontech.atlassian.net/browse/UXE-2340

**Comment by morganajohann** [comment]
Issue resolvida.
