### ISSUE TITLE
Edge function instance com indicacão errada de verificação sintática do json

### ISSUE THREAD

**Issue by paulobaggio** [aziontech/azion-console-kit#769]
json está correto e não necessita do ";"
<img width="1395" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/1470415/93b3ef0e-cb5c-4d7d-99aa-ab0f2226e79b">

**Comment by morganajohann** [comment]
Aberto bug no Jira para correção: https://aziontech.atlassian.net/browse/UXE-2493

**Comment by morganajohann** [comment]
Oi, @paulobaggio! Esse problema foi resolvido na issue: https://aziontech.atlassian.net/browse/UXE-1944. Se quiser dar um check e nos retornar se está correto agora, seria ótimo :)
