### ISSUE TITLE
Home > Edge Applications >  Edit Edge Application  - Error when I try to change the minimum TLS version.

### ISSUE THREAD

**Issue by gabrielnes-azion** [aziontech/azion-console-kit#789]
How to reproduce it : 
1. Go to Edge Application list;
2. Open one edge-application;
3. Try to change the minimum TLS version.

<img width="912" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/c640f4b1-1a62-4374-be57-3f810c3839f7">

**Comment by morganajohann** [comment]
Aberto bug no Jira para ajuste: https://aziontech.atlassian.net/browse/UXE-2494

**Comment by morganajohann** [comment]
Issue resolvida.
