### ISSUE TITLE
Não foi possivel atualizar uma rule do edge-application

### ISSUE THREAD

**Issue by gabrielnes-azion** [aziontech/azion-console-kit#870]
**Describe the bug**
Ao tentar salvar uma rule do console.azion.com pelo console.azion.com, obtive erro ao salvar a regra.

**To Reproduce**
1. Go to 'Edge applications, select an edge application, and go to rules engine'
2. Click on a rule to Edit it.
3. Scroll down to 'Behaviors' and set the following behavior:
Add Response Header:
Content-Security-Policy: default-src 'self' *.azion.com https://storage.googleapis.com cdn.segment.com api.segment.io; frame-src https://feedback.fish *.azion.com https://www.google.com; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content; style-src https://storage.googleapis.com https://console.azion.com https://fonts.azion.com cdn.jsdelivr.net 'unsafe-hashes' 'unsafe-inline'; font-src https://storage.googleapis.com https://console.azion.com https://fonts.azion.com data:; script-src https://storage.googleapis.com *.azion.com https://feedback.fish 'unsafe-inline'; style-src-elem https://storage.googleapis.com *.azion.com https://feedback.fish cdn.jsdelivr.net 'unsafe-inline'; script-src-elem https://storage.googleapis.com *.azion.com https://feedback.fish https://cdn.jsdelivr.net https://cdn.segment.com https://www.google.com https://www.gstatic.com; img-src *
4. Save the rule.
5. See error

**Expected behavior**
Deve salvar a regra similar ao RTM

**Screenshots**
<img width="1434" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/b479f8f9-7611-4117-ab0a-b6622f1edf62">

**Comment by morganajohann** [comment]
Aberto bug no Jira para correção: https://aziontech.atlassian.net/browse/UXE-2495

**Comment by morganajohann** [comment]
@gabrielnes-azion a issue aberta foi arquivada, porque foi detectado que o erro era na API. Com o ajuste feito na API, na issue [ENG-29185](https://aziontech.atlassian.net/browse/ENG-29185), o erro não está mais acontecendo no front. Obrigada por reportar!
