### ISSUE TITLE
Trocar o link de Report issue 

### ISSUE THREAD

**Issue by gabrielnes-azion** [aziontech/azion-console-kit#871]
Ao invés de levar para o link de Report issue para https://github.com/aziontech/azion-console-kit/issues/new que abre a issue sem selecionar o tipo, colocar o link levando  https://github.com/aziontech/azion-console-kit/issues/new/choose para o usuario poder escolher entre bug, feature-request, etc.

**Comment by morganajohann** [comment]
O link de "report issue" vai ser tirado do Console agora que temos o botão de "Send feedback".
Vou deixar essa sugestão em aberto até que essa alteração suba para prod.

**Comment by morganajohann** [comment]
@gabrielnes-azion o link de "report issue" foi retirado do Console. Por conta disso, estou fechando essa issue. Obrigada pelo feedback!
