### ISSUE TITLE
Rule Run Function não está carregando o nome da function na edição

### ISSUE THREAD

**Issue by gabrielnes-azion** [aziontech/azion-console-kit#872]
**Describe the bug**
Ao editar uma regra de run function, o nome da função não está sendo carregado na tela.

**To Reproduce**
1. Go to 'Edge application', edit an edge-app and go to rules engine.
2. Abra uma regra de run function
3. Scroll down to 'Behaviors'
4. O campo da function está aparecendo vazio

**Expected behavior**
Deve apresentar a função que foi configurada pelo usuario.

**Screenshots**
Tela no console:
<img width="1440" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/5c49b669-b956-4beb-9cee-41b620d5ef29">

Tela no RTM atual:
<img width="1440" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/b26a43c7-ed28-4978-ad6f-9a28c108ce08">

**Comment by morganajohann** [comment]
Aberto bug no Jira para ajuste: https://aziontech.atlassian.net/browse/UXE-2497

**Comment by morganajohann** [comment]
@gabrielnes-azion a issue for arquivada, pois o time de QA testou e o erro não estava mais acontecendo. Vou fechar o registro aqui, obrigada por reportar.
