### ISSUE TITLE
Console does not show all purges in Real-Time Purge

### ISSUE THREAD

**Issue by MagnunAVFAzion** [aziontech/azion-console-kit#873]
**Bug Description**
The azion console is not showing the entire purge history.
This occurred when I was testing wildcard purges with the CLI and RTM interface.
The console is only showing the manual purges and the RTM is showing them all.

**To Reproduce**
- Deploy a jamstack application with azion cli (any preset, react for example);
- Open RTM in a tab and console in another;
- Update the application and make a new deploy (CLI will trigger a wildcard purge);
- Go to Real-Time Purge and make a manual wildcard purge to the application domain (APP_DOMAIN/*);
- Check the tabs and notice the list difference;

**Expected behavior**
The purges list must be equal.

**Screenshots**
Below, access to the Console and RTM at the same time.
If you pay attention, also there are differences in the way the information is presented (mix of language, Portuguese and English).

**Console**
<img width="1429" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/103958633/dc876848-1eee-462c-84b1-6a82ff2d2823">

**Rtm**
<img width="1437" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/103958633/4097be74-23ca-4165-a9bc-243404cc73fd">

**Comment by morganajohann** [comment]
Aberto bug no Jira para ajuste: https://aziontech.atlassian.net/browse/UXE-2498

**Comment by morganajohann** [comment]
Oi, @MagnunAVFAzion! A [issue](https://aziontech.atlassian.net/browse/UXE-2498) já foi feita. Quer checar para gente se está de acordo com o esperado?
