### ISSUE TITLE
Getting error "detail: There are some uknown fields: ['phase']" when create or edit Rules Engine

### ISSUE THREAD

**Issue by dayves** [aziontech/azion-console-kit#893]
Hi,
Today Azion's interface changed for me and now I'm getting the error `detail: There are some uknown fields: ['phase']` and I can't create or edit my Rules Engines. There is any way to rollback to the previous version?

**Comment by vinigfer** [comment]
Hi @dayves, thank you for opening an issue. We are aware of the problem and working on a fix. We'll let you know as soon as we deploy a fix for it.
