### ISSUE TITLE
Na aba de edge applications o botão de ações não está funcionando

### ISSUE THREAD

**Issue by hendriksoares** [aziontech/azion-console-kit#895]
![image](https://github.com/aziontech/azion-console-kit/assets/15198158/9d442b73-6850-40b7-b578-7b56fecd46b3)

Na aba de edge applications o botão de ações não está funcionando, no caso á um registro no console dizendo:

 Cannot read properties of null (reading 'toggle')

**Comment by morganajohann** [comment]
Bug aberto no Jira para correção: https://aziontech.atlassian.net/browse/UXE-2559

**Comment by matheus-sunderhus** [comment]
bug solved and fix already available in production.
