### ISSUE TITLE
[console] Edge Service name is missing on resource list tab

### ISSUE THREAD

**Issue by askazion** [aziontech/azion-console-kit#896]
Problem:
Using console,  Edge Services, when I switch to the resources listing, the service name I am editing is missing (I cannot find which service is under edition)

Expected Behavior:
I can see clearly the Service I am editing on any tab. 

Step by Step to Reproduce:
Open session "Edge Services" on left menu.
The Edge Services list will be presented
Click on any item of this list.
You will be editing the item you chose, but the item name will show "Edit Edge Service" (above "Main settings" and "Resources" buttons) (the behavior differs from Edge Applications, for instance, where there it will show the name under edition)
If you click the button "Resources", the Edge Service you are editing will not be clear on any part of the screen:
![service1](https://github.com/aziontech/azion-console-kit/assets/81986523/9de1dcf4-1a0e-4d14-8285-26a42d3d3f6c)
![application1](https://github.com/aziontech/azion-console-kit/assets/81986523/55d9f516-5ebf-49a4-b136-40c1ffb3dd46)

**Comment by morganajohann** [comment]
Bug aberto no Jira para correção: https://aziontech.atlassian.net/browse/UXE-2560

**Comment by matheus-sunderhus** [comment]
bug solved and fix will be available in production next release.
