### ISSUE TITLE
Switch account não atualiza dados da sessão na troca de aba.

### ISSUE THREAD

**Issue by gabrielnes-azion** [aziontech/azion-console-kit#900]
**Describe the bug**
Ao abrir o console em 2 abas e fazer a troca de conta em uma delas (obs: apenas contas Brand, Group, etc), o console passa a exibir informações da sessão da conta selecionada, porém ao voltar para a aba anterior, vemos o navbar apresentando o cliente antigo. Isso da impressão que os dados de um cliente estão vazando para o outro mas trata-se apenas de uma falta de refresh do dado. 

**To Reproduce**
1. Logar com uma conta Brand ou Group.
2. Abra duas abas na mesma pagina.
3. Clique no 'Switch Account' ao lado do logo e mude de conta.
4. Voltr para  a outra aba. Ela ainda estará apresentando a conta anterior.
5. Navegue nas telas. Mesmo recarregando a tela, o nome da conta no navbar permanece o antigo, porém os dados da nova.

**Expected behavior**
Em contas com hierarquia (brand, groups, etc) deve ser validado a conta ativa para atualizar a informação do navbar.

**Screenshots**
<img width="1401" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/cb588751-0944-4a29-94b9-b3189366c718">
<img width="1435" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/39065202/b197c2ce-e07e-4475-aaf1-9533eab8d2c6">

**Comment by morganajohann** [comment]
Bug aberto no Jira para correção: https://aziontech.atlassian.net/browse/UXE-2561
